apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern
  labels:
    role: frontend
    app: frontend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
      app: frontend
  template:
    metadata:
      labels:
        role: frontend
        app: frontend
    spec:
      containers:
        - name: frontend
          image: clarinda1/mern-stack-project-frontend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: react-app-api-base-url
            - name: NODE_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: node-options
