apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern
spec:
  ports:
  - name: backend-port
    port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    role: backend
    app: backend
